name: Build and Deploy API
on:
  push:
    branches:
      - master
    paths:
      - 'API/**'
      - '.github/workflows/Api.yml'

jobs:
  build-and-deploy:
    name: Build, Install, and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: API/functions
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build and Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./API
