name: Build and Deploy API
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: API
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build and Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./API
