name: Build and Deploy Data
on:
  push:
    branches:
      - master
    paths:
      - 'Data/**'
      - '.github/workflows/Data.yml'

jobs:
  build-and-deploy:
    name: Build, Install, and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Data/
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./Data
